# Generated by Django 6.0.2 on 2026-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
