# Generated by Django 6.0.2 on 2026-02-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacydocument',
            name='pharmacy',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='PharmacyDocument',
        ),
    ]
