"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from dotenv import dotenv_values

config = dotenv_values(".env") 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+8u9#7ic@sl12#y1ts!gi^aa-*roa$af*r^a))!_-n4bz26wg$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Used by WebSocket consumers to build absolute media URLs
BASE_URL = "http://localhost:8000"


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'corsheaders',
    'rest_framework',
    'drf_yasg',
    'accounts',
    'rest_framework_simplejwt',
    'celery',
    'django_celery_results',
    'pharmacy',
    'medicine',
    'customer',
    'accountsprofile',
    'DailyRemainder',
    'rest_framework_simplejwt.token_blacklist',
    'adminapis',
    'fomo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Channel layers configuration for WebSockets
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'accounts.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

EMAIL_HOST = 'smtp.gmail.com'  

EMAIL_USE_TLS = True

EMAIL_PORT = 587

EMAIL_HOST_USER = config.get("EMAIL_HOST_USER")
 
EMAIL_HOST_PASSWORD = config.get("EMAIL_HOST_PASSWORD")

# Email timeout settings (in seconds)
EMAIL_TIMEOUT = 30

# Email Backend Configuration
# For development/debugging when SMTP is blocked, set USE_CONSOLE_EMAIL=true in .env
USE_CONSOLE_EMAIL = config.get("USE_CONSOLE_EMAIL", "false").lower() == "true"

if USE_CONSOLE_EMAIL:
    # Console backend - prints emails to console (useful for development)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # SMTP backend - sends real emails
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Celery Configuration
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # Use Redis as broker (recommended)
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ALWAYS_EAGER = False  # Set to True for debugging without Celery worker

# Celery Beat Schedule (Periodic Tasks)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'generate-daily-occurrences': {
        'task': 'DailyRemainder.tasks.generate_daily_occurrences',
        'schedule': crontab(hour=0, minute=0),  # Run daily at midnight
    },
    'check-missed-occurrences': {
        'task': 'DailyRemainder.tasks.check_missed_occurrences',
        'schedule': crontab(minute='*/30'),  # Run every 30 minutes
    },
    'send-reminder-notifications': {
        'task': 'DailyRemainder.tasks.send_reminder_notifications',
        'schedule': crontab(minute='*/5'),  # Run every 5 minutes
    },
    'record-timed-out-fomo': {
        'task': 'fomo.tasks.record_timed_out_requests',
        'schedule': crontab(minute='*/10'),  # Run every 10 minutes
    },
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173","http://127.0.0.1:5173"
]

CORS_ALLOW_CREDENTIALS = True


# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Firebase Cloud Messaging (FCM) Configuration
# To enable push notifications:
# 1. Go to Firebase Console (https://console.firebase.google.com/)
# 2. Navigate to Project Settings > Service Accounts
# 3. Click "Generate New Private Key" and download the JSON file
# 4. Save it as 'firebase-credentials.json' in the project root (same level as manage.py)
# 5. Add firebase-credentials.json to .gitignore (NEVER commit this file!)
FIREBASE_CREDENTIALS_PATH = BASE_DIR / 'firebase-credentials.json'