# Generated by Django 6.0.2 on 2026-02-25 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_lat', models.FloatField(default=0.0)),
                ('patient_lng', models.FloatField(default=0.0)),
                ('radius_km', models.FloatField(default=5.0)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='prescriptions/')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pharmacy.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=20)),
                ('audio', models.FileField(blank=True, null=True, upload_to='pharmacy-audio/')),
                ('text_message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pharmacy.pharmacy')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='medicine.medicinerequest')),
            ],
            options={
                'unique_together': {('request', 'pharmacy')},
            },
        ),
    ]
