# Generated by Django 6.0.2 on 2026-02-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PingRequest',
        ),
    ]
