# Generated by Django 6.0.2 on 2026-02-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyRemainder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmoccurrence',
            name='notified',
            field=models.BooleanField(default=False, help_text='True once a push notification has been sent for this occurrence.'),
        ),
    ]
