# Generated by Django 6.0.2 on 2026-02-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0004_pharmacydocument_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('amount_lost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_opportunities', to='pharmacy.pharmacy')),
            ],
            options={
                'verbose_name_plural': 'Missed Opportunities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
