# Generated by Django 6.0.2 on 2026-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacy_address_pharmacy_created_at_pharmacy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy-profile/'),
        ),
    ]
