# Generated by Django 6.0.2 on 2026-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacy_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydocument',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
